export interface UsuarioAttributes {
  Usuario: string
  Nombre?: string
  Sucursal?: number
  DefEmpresa?: string
  GrupoTrabajo?: string
  Departamento?: string
  Contrasena?: string
  ContrasenaConfirmacion?: string
  ContrasenaFecha?: Date
  ContrasenaModificar?: boolean
  Telefono?: string
  Extencion?: string
  DefAgente?: string
  DefCajero?: string
  DefAlmacen?: string
  DefAlmacenTrans?: string
  DefCtaDinero?: string
  DefCtaDineroTrans?: string
  DefMoneda?: string
  DefProyecto?: string
  DefLocalidad?: string
  DefCliente?: string
  DefActividad?: string
  DefMovVentas?: string
  DefZonaImpuesto?: string
  DefFormaPago?: string
  Afectar: boolean
  Cancelar: boolean
  Desafectar: boolean
  Autorizar?: boolean
  AutorizarVenta?: boolean
  AutorizarCxp?: boolean
  AutorizarGasto?: boolean
  AutorizarDinero?: boolean
  AutorizarPV?: boolean
  AutorizarCompra?: boolean
  AutorizarGestion?: boolean
  AutorizarSeriesLotes?: boolean
  AfectarOtrosMovs: boolean
  CancelarOtrosMovs: boolean
  ConsultarOtrosMovs: boolean
  ConsultarOtrosMovsGrupo?: boolean
  ConsultarOtrasEmpresas?: boolean
  ConsultarOtrasSucursales?: boolean
  AccesarOtrasSucursalesEnLinea?: boolean
  AfectarOtrasSucursalesEnLinea?: boolean
  ModificarOtrosMovs: boolean
  ModificarVencimientos: boolean
  ModificarEntregas: boolean
  ModificarFechaRequerida?: boolean
  ModificarEnvios: boolean
  ModificarReferencias: boolean
  ModificarAlmacenEntregas: boolean
  ModificarSituacion: boolean
  ModificarAgente: boolean
  ModificarUsuario: boolean
  ModificarListaPrecios: boolean
  ModificarZonaImpuesto: boolean
  ModificarSucursalDestino?: boolean
  ModificarProyUENActCC?: boolean
  AgregarCteExpress: boolean
  AgregarArtExpress: boolean
  Costos: boolean
  BloquearCostos?: boolean
  VerInfoDeudores: boolean
  VerInfoAcreedores: boolean
  VerComisionesPendientes: boolean
  BloquearEncabezadoVenta: boolean
  BloquearCxcCtaDinero: boolean
  BloquearCxpCtaDinero: boolean
  BloquearDineroCtaDinero: boolean
  EnviarExcel: boolean
  ImprimirMovs: boolean
  PreliminarMovs: boolean
  Reservar: boolean
  DesReservar: boolean
  Asignar: boolean
  DesAsignar: boolean
  ModificarAlmacenPedidos: boolean
  ModificarConceptos: boolean
  ModificarReferenciasSiempre: boolean
  ModificarAgenteCxcPendiente: boolean
  ModificarMovsNominaVigentes?: boolean
  BloquearPrecios: boolean
  BloquearDescGlobal?: boolean
  BloquearDescLinea?: boolean
  BloquearCondiciones: boolean
  BloquearAlmacen: boolean
  BloquearMoneda: boolean
  BloquearAgente: boolean
  BloquearFechaEmision: boolean
  BloquearProyecto: boolean
  BloquearFormaPago?: boolean
  Oficina?: string
  DefArtTipo?: string
  DefUnidad?: string
  AbrirCajon?: boolean
  BloquearCobroInmediato?: boolean
  ConsultarCompraPendiente?: boolean
  AccesoTotalCuentas?: boolean
  Estatus: string
  UltimoCambio?: Date
  Alta?: Date
  Configuracion?: string
  Acceso?: string
  TieneMovimientos?: boolean
  Refacturar?: boolean
  DefListaPreciosEsp?: string
  LimiteTableroControl?: number
  CteInfo?: boolean
  CteBloquearOtrosDatos?: boolean
  ArtBloquearOtrosDatos?: boolean
  CteSucursalVenta?: boolean
  CtaDineroInfo?: boolean
  ImpresionInmediata?: boolean
  MostrarCampos?: boolean
  AsistentePrecios?: boolean
  CambioValidarCobertura?: boolean
  CambioNormatividad?: boolean
  CambioEditarCobertura?: boolean
  CambioVerPosicionEmpresa?: boolean
  CambioVerPosicionSucursal?: boolean
  CambioVerPosicionOtraSucursal?: boolean
  CambioAutorizarOperacionLimite?: boolean
  AutoDobleCapturaPrecios?: boolean
  AutoArtGrupo?: string
  AutoAgregarRecaudacionConsumo?: boolean
  AutoDiesel?: boolean
  BloquearActividad?: boolean
  UEN?: number
  eMail?: string
  CteMov?: boolean
  CteArt?: boolean
  ProvMov?: boolean
  ArtMov?: boolean
  DefContUso?: string
  BloquearContUso?: boolean
  Observaciones?: string
  TraspasarTodo?: boolean
  BloquearNotasNegativas?: boolean
  ModificarSerieLoteProp?: boolean
  NominaEliminacionParcial?: boolean
  ModificarPropiedadesLotes?: boolean
  PVAbrirCajonSiempre?: boolean
  PVBloquearEgresos?: boolean
  PVCobrarNotasEstatusBorrador?: boolean
  PVModificarEstatusBorrador?: boolean
  BloquearPersonalCfg?: boolean
  BloquearFacturacionDirecta?: boolean
  BloquearInvSalidaDirecta?: boolean
  Idioma?: string
  ModificarDatosVIN?: boolean
  ModificarDatosCliente?: boolean
  CxcExpress?: boolean
  CxpExpress?: boolean
  Cliente?: string
  SubModuloAtencion?: string
  BloquearCancelarFactura?: boolean
  CambioPresentacionExpress?: boolean
  ModificarConsecutivos?: boolean
  ModificarVINFechaBaja?: boolean
  ModificarVINFechaPago?: boolean
  ModificarVINAccesorio?: boolean
  PVEditarNota?: boolean
  ModificarDescGlobalImporte?: boolean
  ConsultarClientesOtrosAgentes?: boolean
  ACLCUsoEspecifico?: string
  ACEditarTablaAmortizacion?: boolean
  PlantillasOffice?: boolean
  ConfigPlantillasOffice?: boolean
  ACTasaGrupo?: string
  CambioAgregarBeneficiarios?: boolean
  AgregarConceptoExpress?: boolean
  BloquearArtMaterial?: boolean
  InfoPath?: boolean
  InfoPathExe?: string
  FEA?: boolean
  FEACertificado?: string
  FEALlave?: string
  ContrasenaNuncaExpira?: boolean
  Menu?: string
  MenuAccesoTotal?: boolean
  BloquearPDF?: boolean
  VerificarOrtografia?: boolean
  ContSinOrigen?: boolean
  UnidadOrganizacional?: string
  ProyectoMov?: boolean
  CompraDevTodo?: boolean
  BloquearWebContenido?: boolean
  BloquearWebHTML?: boolean
  DBMailPerfil?: string
  UltimoAcceso?: Date
  BloquearSituacionUsuario?: boolean
  InformacionConfidencial?: boolean
  PerfilForma?: string
  Licenciamiento?: string
  SituacionArea?: string
  ModificarTipoImpuesto?: boolean
  AgregarProvExpress?: boolean
  ProyMov?: boolean
  ContrasenaWeb?: string
  VisibleWeb?: string
  AutorizacionesMayores?: string
  BloquearTipoCambio?: boolean
  AfectarCORTE?: boolean
  ModificarPosicionSugeridaWMS?: boolean
  ModificarAgenteWMS?: boolean
  OPORTPlantilla?: string
  Personal?: string
  INFORPerfil?: string
  INFORSupervisor: boolean
  ReferenciaIntelisisService?: string
  ISMESNotificarError?: boolean
  POSPerfil?: string
  POSEsSupervisor?: boolean
  MESAcceso: boolean
  MESEstructura: boolean
  MESPlanificacion: boolean
  MESVariantes: boolean
  MESScheduling: boolean
  VicAgregaCondic?: boolean
  VicActualizaCondic?: boolean
  VicInactivaCondic?: boolean
  VicEliminaCondic?: boolean
  vic_VerPlanoGramaDiseno?: boolean
  vic_VerPlanoGramaProduccion?: boolean
  vic_CopiarAccionesPlanoGrama?: boolean
  vic_ActualizarPlanoGrama?: boolean
  vic_EliminarPlanoGrama?: boolean
  vic_AccionesPlanoGrama?: boolean
  AutorizaAltaTarima?: boolean
  CE?: boolean
  AutorizarCE?: boolean
  CEBloquearCalif?: boolean
  DefPersonal?: string
  DesafectarAsig?: boolean
  PeriodoEvalWEB?: boolean
  ModNumCiclo?: boolean
  ModMatricula?: boolean
  CreditosSugeridos?: boolean
  CEHorarioAlumnoRegMat?: boolean
  CENoGenerarCuotasJob?: boolean
  AgregarAlumnosCyA?: boolean
  CEPlandeEstudios?: boolean
  CEAfectarMovControlFechas?: boolean
  CEContrasenaPortal?: string
  CEUltimasContrasenasPortal1?: string
  CEUltimasContrasenasPortal2?: string
  CEUltimasContrasenasPortal3?: string
  CEUltimasContrasenasPortal4?: string
  CEUltimasContrasenasPortal5?: string
  CEUltimasContrasenasPortal6?: string
  CECaducaContrasenaPortal?: Date
  RefBancoTipo?: string
  RefBancoTipo1?: string
  RefBancoTipo2?: string
  RefBancoTipo3?: string
  RefBancoTipo4?: string
  RefBancoTipo5?: string
  RefBancoTipo6?: string
  BloqueaCPortal?: boolean
  DesafectarBaja?: boolean
  UsuarioSesionPortal?: string
  UsuarioPerfilPortal?: string
  PerfilPortal?: string
  EstatusPortal?: string
  ModificarPerfilPortal?: boolean
  ModificarEstatusPortal?: boolean
  eMailInt?: string
  IdiomaPortal?: string
  vicRenovarEspecial?: boolean
  vic_BajaContrato?: boolean
  VicRealizarApartado?: boolean
  VicModificarFechasApartado?: boolean
  VicRealizarDesapartado?: boolean
  VicEditarContrato?: boolean
  vicParametrizacion?: boolean
  vicAccesoHerrEnvioMail?: boolean
  vicConfigHerrEnvioMail?: boolean
  vicLocalUsuarioPS?: boolean
  vicFusDivLocales: boolean
  vicGenerarComision?: boolean
  vicVentaDepRefdo?: boolean
  vicLogPN?: boolean
  vicGenerarComplementoRenovacio?: boolean
  VicHerramientaFechaProximoMov?: boolean
  VicHerramientaCondicionPago?: boolean
  vicComisiones?: boolean
  vicGFAAutorizaComisiones?: boolean
  vicGFAAfectaComisiones?: boolean
  Pass?: string
  PassNuevo?: string
  ValidaSucursalUsuario?: boolean
  POSCodigoAut?: string
  OmitirMovsReevaluacion?: boolean
  UsuarioTipo?: string
  BitRol?: boolean
  UsuarioSalud?: boolean
}

export interface roleInterface {
  role: 'root' | 'admin' | 'user' | 'logistic' | 'marketing' | 'operations'
}

export interface locationInterface {
  location: 'GDL' | 'CDMX' | 'MXL' | 'TARA'
}

export interface UserInterface {
  id?: number
  username: string
  password: string
  role: roleInterface
  location: locationInterface
  mustUpdatePassword: boolean
  createdAt?: Date
  updatedAt?: Date
}
